### ISSUE TITLE
Help with running multibit experiment

### ISSUE THREAD

**Issue by bangawayoo** [facebookresearch/three_bricks#1]
Hi. 
Thank you for the great work!

I am trying to run the multibit experiment to compute the bit error.
When running the original scripts with minor modification on the model (I am using "meta-llama/Llama-2-7b-hf"), the predicted messages seem to be biased on the payload=0.

This is the shell I ran with payload=2:
```
MODEL_NAME="meta-llama/Llama-2-7b-hf"
python main_watermark.py --model_name $MODEL_NAME \
    --prompt_type guanaco --prompt_path data/alpaca_data.json --nsamples 5 --batch_size 1 \
    --method openai --temperature 1.0 --seeding hash --ngram 2 --method_detect openai --scoring_method v2 \
    --payload 2 --payload_max 4 \
    --output_dir output/
```

This is the output on 5 samples:

> {"text_index": 0, "num_token": 81, "score": 1.9244784116744995, "pvalue": 7.516629810371665e-11, "all_pvalues": [1.503325962074333e-11, 0.5525190716800495, 0.6241409451094209, 0.5133621236606887, 0.873804904595953], "score_sbert": 0.16323570907115936, **"payload": 0}**
{"text_index": 1, "num_token": 50, "score": 1.58894681930542, "pvalue": 0.000816704994070272, "all_pvalues": [0.00016339438554069307, 0.6806735335887873, 0.7362280176118632, 0.820089764602793, 0.008716973909117734], "score_sbert": 0.2772168517112732, **"payload": 0}**
{"text_index": 2, "num_token": 80, "score": 1.4883081912994385, "pvalue": 0.0003016562619195806, "all_pvalues": [6.033853342182464e-05, 0.007914174637055299, 0.7406979451606139, 0.7050356946728789, 0.6615083648825413], "score_sbert": 0.6990629434585571, **"payload": 0}**
{"text_index": 3, "num_token": 44, "score": 1.396287441253662, "pvalue": 0.04103599245682854, "all_pvalues": [0.01223631927460033, 0.008345329985554676, 0.8391204944655659, 0.6738269627638542, 0.24927330400448738], "score_sbert": 0.4065162241458893, **"payload": 1}**
{"text_index": 4, "num_token": 68, "score": 2.267747402191162, "pvalue": 1.0296207824021187e-14, "all_pvalues": [2.0592415648042375e-15, 0.8530005386184477, 0.21813631427763727, 0.16060655616336122, 0.18849879787000062], "score_sbert": 0.48217082023620605, **"payload": 0}**

Would you help me out? 

Thanks!

**Comment by pierrefdz** [comment]
Hi @bangawayoo,
This seems strange indeed, and I don't have an answer yet. I'll try to look into it in the following days, keep me updated if you find anything.

**Comment by pierrefdz** [comment]
Hi @bangawayoo any news on this?
When running the code on my side I don't observe what you observe.

> {"text_index": 0, "num_token": 178, "score": 1.1933594942092896, "pvalue": 0.03476400722862438, "all_pvalues": [0.7922989807811949, 0.41452019688338615, 0.007051551401072557, 0.39069741644686173, 0.9480349970743382], "score_sbert": 0.6643755435943604, "payload": 2}
{"text_index": 1, "num_token": 44, "score": 1.1796373128890991, "pvalue": 0.4713904801763794, "all_pvalues": [0.6141780622673244, 0.2577187734593871, 0.11970751154920739, 0.8722526365630205, 0.4845644545051258], "score_sbert": 0.8104264736175537, "payload": 2}
{"text_index": 2, "num_token": 198, "score": 1.0907080173492432, "pvalue": 0.4201101781412674, "all_pvalues": [0.23135968932515064, 0.10325472459574443, 0.808775388252057, 0.14842720858385436, 0.921933113764955], "score_sbert": 0.7797485589981079, "payload": 1}
{"text_index": 3, "num_token": 240, "score": 1.1282325983047485, "pvalue": 0.12735961299525234, "all_pvalues": [0.7790667134828514, 0.6597800557473217, 0.03920002784314521, 0.026878513727784305, 0.07987654312940413], "score_sbert": 0.8741214275360107, "payload": 3}
{"text_index": 4, "num_token": 221, "score": 1.213386058807373, "pvalue": 0.006884401808360807, "all_pvalues": [0.07092060308900801, 0.27417427129232463, 0.0013806876983399976, 0.5554186540022319, 0.44594089549148597], "score_sbert": 0.0995001420378685, "payload": 2}

**Comment by bangawayoo** [comment]
Hi. 
I don't have an update on this. I did read through the implementation, but everything seemed all right. 

Just to clarify, your results are also unexpected given that the predicted payloads are not all predicting the same value, right?  Was the argument for payload `--payload 2` ?

**Comment by pierrefdz** [comment]
Would you be able to share your code?

The watermark strength depends a lot on the model. For instruction tuned model (i used llama 2 7b chat) you typically need higher temperature for the scheme of Aaronson, and higher delta for the one of Kitchenbaueur. This explains the high p-values and therefore the fact that it does not always predict payload 2 (which was indeed the argument).

**Comment by bangawayoo** [comment]
Hi @pierrefdz, 
I apologize for the confusion. 
I was reproducing the results yesterday and surprisingly everything is working fine!
<details>
<summary>Results for payload=3, delta=4.0</summary>
As expected, all predicted payloads are 3. 
> {"text_index": 0, "num_token": 34, "score": 2.543719530105591, "pvalue": 2.1036422796479004e-10, "all_pvalues": [0.44115517536132737, 0.005448780565635643, 0.5455996640819742, 4.207284559295801e-11, 0.12190968317800745], "score_sbert": 0.10168936848640442, "payload": 3, "acc": 0.6666666666666666, "match": 0.0}
> {"text_index": 1, "num_token": 40, "score": 1.550395131111145, "pvalue": 0.005852771822431491, "all_pvalues": [0.31326830961066027, 0.7226518464795865, 0.5630816416087423, 0.0011733044224733664, 0.1672648554712578], "score_sbert": 0.6900381445884705, "payload": 3, "acc": 0.6666666666666666, "match": 0.0}
> {"text_index": 2, "num_token": 75, "score": 1.565458059310913, "pvalue": 5.810519367266398e-05, "all_pvalues": [0.5758181831414055, 0.46679646087664073, 0.7701897362048917, 1.162130884105661e-05, 0.6254992105543195], "score_sbert": 0.5417057871818542, "payload": 3, "acc": 0.6666666666666666, "match": 0.0}
> {"text_index": 3, "num_token": 39, "score": 2.077378749847412, "pvalue": 3.869848795711798e-07, "all_pvalues": [0.3961806171561437, 0.15322542391649258, 0.5136377007124584, 7.739697591423596e-08, 0.2761402095962206], "score_sbert": 0.3133828639984131, "payload": 3, "acc": 0.6666666666666666, "match": 0.0}
> {"text_index": 4, "num_token": 46, "score": 2.231442928314209, "pvalue": 6.279396266735629e-10, "all_pvalues": [0.2787383297429447, 0.5968674117907384, 0.3254707622391647, 1.2558792533471257e-10, 0.1431420898173676], "score_sbert": 0.015573520213365555, "payload": 3, "acc": 0.6666666666666666, "match": 0.0}

</details>
I think I must have been seeing the old results (`./output/scores.jsonl`), which was created the first time I ran your script with payload set as 0. 


FYI, the code is [here](https://github.com/bangawayoo/three_bricks/tree/llama-2) with only minor modifications in tokenizer configuration to run on LLaMA-2. 

Thank you for helping out.
